// Sample bookings data for demonstration
export const bookingsData = [
    {
      id: "b1",
      client: {
        firstName: "Emma",
        lastName: "Johnson",
        email: "emma.j@example.com",
        phone: "(555) 123-4567",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Gel Manicure",
        category: "manicure",
        duration: "45 min",
        price: 35,
      },
      dateTime: "2025-03-12T10:00:00",
      status: "booked",
      notes: "First-time client, prefers pastel colors",
      updatedAt: "2025-03-10T14:30:00",
    },
    {
      id: "b2",
      client: {
        firstName: "Sophia",
        lastName: "Garcia",
        email: "sophia.g@example.com",
        phone: "(555) 234-5678",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Volume Lash Extensions",
        category: "eyelashes",
        duration: "120 min",
        price: 150,
      },
      dateTime: "2025-03-12T13:00:00",
      status: "checked-in",
      notes: "Allergic to latex adhesive, use alternative",
      updatedAt: "2025-03-12T13:05:00",
    },
    {
      id: "b3",
      client: {
        firstName: "Olivia",
        lastName: "Smith",
        email: "olivia.s@example.com",
        phone: "(555) 345-6789",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Spa Pedicure",
        category: "pedicure",
        duration: "75 min",
        price: 65,
      },
      dateTime: "2025-03-11T15:30:00",
      status: "completed",
      notes: "Regular client, prefers hot stone massage",
      updatedAt: "2025-03-11T16:45:00",
    },
    {
      id: "b4",
      client: {
        firstName: "Ava",
        lastName: "Williams",
        email: "ava.w@example.com",
        phone: "(555) 456-7890",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Eyebrow Threading",
        category: "eyebrows",
        duration: "20 min",
        price: 18,
      },
      dateTime: "2025-03-11T11:00:00",
      status: "cancelled",
      notes: "Cancelled due to illness",
      updatedAt: "2025-03-10T19:20:00",
    },
    {
      id: "b5",
      client: {
        firstName: "Isabella",
        lastName: "Brown",
        email: "isabella.b@example.com",
        phone: "(555) 567-8901",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Basic Manicure",
        category: "manicure",
        duration: "30 min",
        price: 25,
      },
      dateTime: "2025-03-10T14:00:00",
      status: "no-show",
      notes: "",
      updatedAt: "2025-03-10T14:30:00",
    },
    {
      id: "b6",
      client: {
        firstName: "Mia",
        lastName: "Jones",
        email: "mia.j@example.com",
        phone: "(555) 678-9012",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Lash Lift",
        category: "eyelashes",
        duration: "45 min",
        price: 65,
      },
      dateTime: "2025-03-13T09:30:00",
      status: "booked",
      notes: "Sensitive eyes, use gentle formula",
      updatedAt: "2025-03-09T10:15:00",
    },
    {
      id: "b7",
      client: {
        firstName: "Charlotte",
        lastName: "Miller",
        email: "charlotte.m@example.com",
        phone: "(555) 789-0123",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Gel Pedicure",
        category: "pedicure",
        duration: "60 min",
        price: 50,
      },
      dateTime: "2025-03-13T11:00:00",
      status: "booked",
      notes: "",
      updatedAt: "2025-03-08T16:40:00",
    },
    {
      id: "b8",
      client: {
        firstName: "Amelia",
        lastName: "Davis",
        email: "amelia.d@example.com",
        phone: "(555) 890-1234",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Eyebrow Tinting",
        category: "eyebrows",
        duration: "30 min",
        price: 25,
      },
      dateTime: "2025-03-13T14:00:00",
      status: "booked",
      notes: "Prefers medium brown tint",
      updatedAt: "2025-03-09T11:20:00",
    },
    {
      id: "b9",
      client: {
        firstName: "Harper",
        lastName: "Wilson",
        email: "harper.w@example.com",
        phone: "(555) 901-2345",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Classic Lash Extensions",
        category: "eyelashes",
        duration: "90 min",
        price: 120,
      },
      dateTime: "2025-03-14T10:00:00",
      status: "booked",
      notes: "",
      updatedAt: "2025-03-07T15:10:00",
    },
    {
      id: "b10",
      client: {
        firstName: "Evelyn",
        lastName: "Moore",
        email: "evelyn.m@example.com",
        phone: "(555) 012-3456",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Spa Manicure",
        category: "manicure",
        duration: "60 min",
        price: 45,
      },
      dateTime: "2025-03-14T13:30:00",
      status: "booked",
      notes: "Birthday treat, add complimentary glass of champagne",
      updatedAt: "2025-03-08T09:45:00",
    },
    {
      id: "b11",
      client: {
        firstName: "Abigail",
        lastName: "Taylor",
        email: "abigail.t@example.com",
        phone: "(555) 123-4567",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Eyebrow Waxing",
        category: "eyebrows",
        duration: "15 min",
        price: 15,
      },
      dateTime: "2025-03-09T16:00:00",
      status: "completed",
      notes: "",
      updatedAt: "2025-03-09T16:15:00",
    },
    {
      id: "b12",
      client: {
        firstName: "Elizabeth",
        lastName: "Anderson",
        email: "elizabeth.a@example.com",
        phone: "(555) 234-5678",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Basic Pedicure",
        category: "pedicure",
        duration: "45 min",
        price: 35,
      },
      dateTime: "2025-03-09T14:30:00",
      status: "completed",
      notes: "Has diabetes, extra care with tools",
      updatedAt: "2025-03-09T15:15:00",
    },
    {
      id: "b13",
      client: {
        firstName: "Sofia",
        lastName: "Thomas",
        email: "sofia.t@example.com",
        phone: "(555) 345-6789",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Volume Lash Extensions",
        category: "eyelashes",
        duration: "120 min",
        price: 150,
      },
      dateTime: "2025-03-08T10:00:00",
      status: "completed",
      notes: "",
      updatedAt: "2025-03-08T12:00:00",
    },
    {
      id: "b14",
      client: {
        firstName: "Avery",
        lastName: "Jackson",
        email: "avery.j@example.com",
        phone: "(555) 456-7890",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Gel Manicure",
        category: "manicure",
        duration: "45 min",
        price: 35,
      },
      dateTime: "2025-03-08T13:30:00",
      status: "completed",
      notes: "Prefers dark colors",
      updatedAt: "2025-03-08T14:15:00",
    },
    {
      id: "b15",
      client: {
        firstName: "Ella",
        lastName: "White",
        email: "ella.w@example.com",
        phone: "(555) 567-8901",
        avatar: "/placeholder.svg?height=32&width=32",
      },
      service: {
        name: "Eyebrow Threading",
        category: "eyebrows",
        duration: "20 min",
        price: 18,
      },
      dateTime: "2025-03-08T15:00:00",
      status: "completed",
      notes: "",
      updatedAt: "2025-03-08T15:20:00",
    },
  ]
  
  